### ISSUE TITLE
image gone from xda

### ISSUE THREAD

**Issue by BrianEdmonds** [justindriggers/android_device_glass_glass-1#1]
I'm playing with a Glass device, and was hoping to flash it with the AOSP image you posted to XDA a few years back, but they seem to have lost it. (My downloads just get 401 Gone.) Any chance you still have a copy around I could get ahold of?

**Comment by justindriggers** [comment]
The [download](https://forum.xda-developers.com/devdb/project/dl/?id=18094) seems to work just fine for me. Here's a [link to download from Google Drive](https://drive.google.com/file/d/1G-8EwqFkGzHqQVRbhzU7XGV3dXz9SrCW/view?usp=sharing).

**Comment by BrianEdmonds** [comment]
Odd, it definitely was failing reliably for me. I did get part of a zip file once, then nothing after that. Thanks for the Drive link. I'm downloading it now, and will be trying it out momentarily...

**Comment by BrianEdmonds** [comment]
And, it's up! Thanks so much for the incredibly fast and helpful response! :)

**Comment by justindriggers** [comment]
Good to hear! It can't do much, but it's fun to play around with.
